version: '3.0'
services:
  rasa:
    image: rasa/rasa:main-spacy-en
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run --network="host"
  actions:
    image: dockingtoaster/rasa-action-railway:0.0.1
    ports:
      - 5055:5055
    expose: [5005]
  duckling:
    image: rasa/duckling
    ports:
      - 8000:8000
