version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.5.1-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  actions:
    image: <image:tag>
    expose: 5055
  app:
    image: <image:tag>
    expose: 8080
  duckling:
    image: rasa/duckling
    ports:
      - 8000:8000
